package com.nationwide.nf.rp.util;

import org.springframework.stereotype.Component;

/**
 * Created by jorgej2 on 6/30/2017.
 * <p>
 * Date         Modifier            Description
 * ----         ---------           ------------
 * 02/08/2019   Dave Abrams         Added new filenet properties: plan type 457 and percent per RP3434
 */
@Component
public class RetrieveDocumentRequest {

    public String create() {
        String retrieveDocumentRequestTemplate = new String(REQUEST);
        return retrieveDocumentRequestTemplate;
    }

    private static String REQUEST =
            "<soap:Envelope xmlns:soap=\"http://www.w3.org/2003/05/soap-envelope\" xmlns:oas=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\" xmlns:doc=\"http://nationwide.com/schemas/Communication/iaa7_1/Content/DocumentManagement_1\" xmlns:wsa=\"http://www.w3.org/2005/08/addressing\" xmlns:wsaw=\"http://www.w3.org/2006/05/addressing/wsdl\">\n" +
                    "   <soap:Header>\n" +
                    "      <oas:Security>\n" +
                    "         <oas:UsernameToken>\n" +
                    "            <oas:Username>sgkynt</oas:Username>\n" +
                    "            <oas:Password>Password1</oas:Password>\n" +
                    "         </oas:UsernameToken>\n" +
                    "         >\n" +
                    "      </oas:Security>\n" +
                    "   </soap:Header>\n" +
                    "   <soap:Body>\n" +
                    "      <doc:retrieveDocument>\n" +
                    "         <doc:ConsumerID>NF_KEYNOTE</doc:ConsumerID>\n" +
                    "         <doc:DocumentKey>\n" +
                    "            <doc:Name>Z_Batch_Number</doc:Name>\n" +
                    "            <doc:Value>ljc0627_002</doc:Value>\n" +
                    "         </doc:DocumentKey>\n" +
                    "         <doc:ReturnProperties>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Id</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>App_Document_ID</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Z_Batch_Number</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Agreement_Number</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Street_Address</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>City</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Zip_Code</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>SSN_Type</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Advisor_Number</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>State</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>FirstName</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>LastName</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Mailing_City</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Mailing_Zip_Code</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Mailing_State</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Date_of_Birth</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Home_Phone</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Gender</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>EmailAddress</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Marital_Status</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Mailing_Street_Address</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Government_ID_Type</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Business_Phone</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>ID_Date_Issued</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Government_ID_Number</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>ID_Expiration_Date</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>k_403_b</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Dollar_Amount_403_b</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Percent_403_b</doc:Name>\n" +         //dabrams added 20190208
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Roth_403_b</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Dollar_Amount_Roth_403_b</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Percent_Roth_403_b</doc:Name>\n" +     //dabrams added 20190208
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>k_457_b</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Dollar_Amount_457_b</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Percent_457</doc:Name>\n" +            //dabrams added 20190208
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Roth_457</doc:Name>\n" +               //dabrams added 20190208
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Dollar_Amount_Roth_457</doc:Name>\n" + //dabrams added 20190208
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Percent_Roth_457</doc:Name>\n" +       //dabrams added 20190208
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Hire_Date</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>County</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>School_District_1</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>School_District_2</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>School_District_3</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>School_District_4</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>School_District_5</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>School_District_6</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>School_District_7</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>School_District_8</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>School_District_9</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>School_District_10</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>School_District_1</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>School_District_11</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>School_District_12</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>School_District_13</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>School_District_14</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>School_District_15</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>School_District_16</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>School_District_17</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Employment_Status</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Occupation_Position</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Annual_Income</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Tax_Bracket</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Net_Worth</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Investment_Objective</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Risk_Exposure</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Investment_Experience</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Source_of_Earnings</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Related_Empl_Broker_Dealer</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Name_of_B_D_relative</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Relationship_to_B_D_Empl</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Empl_of_another_B_D</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Related_Empl_of_another_B_D</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>B_D_Name</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>B_D_Name_related</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Other_B_D_Empl_name</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Other_B_D_relationship</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>FINRA</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>FINRA_Affiliation_Name</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Publicly_traded_company</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Publicly_traded_company_name</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Country_of_Citizenship</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "           <doc:ReturnProperty>\n" +
                    "               <doc:Name>Empl_of_this_Broker_Dealer</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Foreign_financial_institution</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Private_banking_account</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Foreign_bank</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Politically_exposed_person</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "            <doc:ReturnProperty>\n" +
                    "               <doc:Name>Plan_ID_Number</doc:Name>\n" +
                    "            </doc:ReturnProperty>\n" +
                    "         </doc:ReturnProperties>\n" +
                    "         <doc:ReturnAttachments>\n" +
                    "            <doc:ReturnAttachment>\n" +
                    "               <doc:Type>Content</doc:Type>\n" +
                    "            </doc:ReturnAttachment>\n" +
                    "         </doc:ReturnAttachments>\n" +
                    "      </doc:retrieveDocument>\n" +
                    "   </soap:Body>\n" +
                    "</soap:Envelope>";
}
